name: Bot Discord EsLint
on: [ push ]
jobs:
  ESLint-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g eslint
      - run: eslint --init
      - run: eslint app.js
